/**
 * Built-in Typst bibliography styles.
 * @see https://typst.app/docs/reference/model/bibliography/
 */
export interface CitationStyle {
	/** Value for `#bibliography(style: "...")`. */
	id: string;
	/** Human-readable label in the settings UI. */
	label: string;
}

export const CITATION_STYLES: readonly CitationStyle[] = [
	{ id: "ieee", label: "IEEE" },
	{ id: "apa", label: "APA" },
	{ id: "mla", label: "MLA" },
	{ id: "chicago-author-date", label: "Chicago (author-date)" },
	{ id: "chicago-notes", label: "Chicago (notes)" },
	{ id: "chicago-fullnotes", label: "Chicago (full notes)" },
	{ id: "chicago-shortened-notes", label: "Chicago (shortened notes)" },
	{ id: "harvard-cite-them-right", label: "Harvard (Cite Them Right)" },
	{ id: "vancouver", label: "Vancouver" },
	{ id: "vancouver-superscript", label: "Vancouver (superscript)" },
	{ id: "american-physics-society", label: "American Physical Society" },
	{ id: "american-chemical-society", label: "American Chemical Society" },
	{ id: "american-medical-association", label: "American Medical Association" },
	{ id: "nature", label: "Nature" },
	{ id: "cell", label: "Cell" },
	{ id: "association-for-computing-machinery", label: "ACM" },
	{ id: "modern-language-association", label: "Modern Language Association" },
	{ id: "modern-language-association-8", label: "MLA 8th edition" },
	{ id: "american-psychological-association", label: "American Psychological Association" },
	{ id: "american-sociological-association", label: "American Sociological Association" },
	{ id: "american-political-science-association", label: "American Political Science Association" },
	{ id: "american-institute-of-physics", label: "American Institute of Physics" },
	{ id: "american-institute-of-aeronautics-and-astronautics", label: "AIAA" },
	{ id: "american-geophysical-union", label: "American Geophysical Union" },
	{ id: "american-meteorological-society", label: "American Meteorological Society" },
	{ id: "american-physiological-society", label: "American Physiological Society" },
	{ id: "american-society-for-microbiology", label: "American Society for Microbiology" },
	{ id: "american-society-of-civil-engineers", label: "ASCE" },
	{ id: "american-society-of-mechanical-engineers", label: "ASME" },
	{ id: "american-anthropological-association", label: "American Anthropological Association" },
	{ id: "alphanumeric", label: "Alphanumeric" },
	{ id: "angewandte-chemie", label: "Angewandte Chemie" },
	{ id: "annual-reviews", label: "Annual Reviews" },
	{ id: "annual-reviews-author-date", label: "Annual Reviews (author-date)" },
	{ id: "associacao-brasileira-de-normas-tecnicas", label: "ABNT (Brazil)" },
	{ id: "biomed-central", label: "BioMed Central" },
	{ id: "bristol-university-press", label: "Bristol University Press" },
	{ id: "british-medical-journal", label: "BMJ" },
	{ id: "copernicus", label: "Copernicus" },
	{ id: "council-of-science-editors", label: "CSE (numeric)" },
	{ id: "council-of-science-editors-author-date", label: "CSE (author-date)" },
	{ id: "current-opinion", label: "Current Opinion" },
	{ id: "deutsche-gesellschaft-für-psychologie", label: "DGPs (Deutsch)" },
	{ id: "deutsche-sprache", label: "Deutsche Sprache" },
	{ id: "elsevier-harvard", label: "Elsevier Harvard" },
	{ id: "elsevier-vancouver", label: "Elsevier Vancouver" },
	{ id: "elsevier-with-titles", label: "Elsevier (numeric, with titles)" },
	{ id: "frontiers", label: "Frontiers" },
	{ id: "future-medicine", label: "Future Medicine" },
	{ id: "future-science", label: "Future Science Group" },
	{ id: "gb-7714-2005-numeric", label: "GB/T 7714-2005 (numeric)" },
	{ id: "gb-7714-2015-author-date", label: "GB/T 7714-2015 (author-date)" },
	{ id: "gb-7714-2015-note", label: "GB/T 7714-2015 (note)" },
	{ id: "gb-7714-2015-numeric", label: "GB/T 7714-2015 (numeric)" },
	{ id: "gost-r-705-2008-numeric", label: "GOST R 7.0.5-2008" },
	{ id: "institute-of-electrical-and-electronics-engineers", label: "IEEE (full name)" },
	{ id: "institute-of-physics-numeric", label: "Institute of Physics" },
	{ id: "iso-690-author-date", label: "ISO-690 (author-date)" },
	{ id: "iso-690-numeric", label: "ISO-690 (numeric)" },
	{ id: "karger", label: "Karger" },
	{ id: "mary-ann-liebert-vancouver", label: "Mary Ann Liebert Vancouver" },
	{ id: "modern-humanities-research-association", label: "MHRA" },
	{ id: "modern-humanities-research-association-notes", label: "MHRA (notes)" },
	{ id: "multidisciplinary-digital-publishing-institute", label: "MDPI" },
	{ id: "pensoft", label: "Pensoft" },
	{ id: "public-library-of-science", label: "PLOS" },
	{ id: "royal-society-of-chemistry", label: "Royal Society of Chemistry" },
	{ id: "sage-vancouver", label: "SAGE Vancouver" },
	{ id: "sist02", label: "SIST02 (日本語)" },
	{ id: "spie", label: "SPIE" },
	{ id: "springer-basic", label: "Springer Basic (numeric)" },
	{ id: "springer-basic-author-date", label: "Springer Basic (author-date)" },
	{ id: "springer-fachzeitschriften-medizin-psychologie", label: "Springer (Deutsch)" },
	{ id: "springer-humanities-author-date", label: "Springer Humanities" },
	{ id: "springer-lecture-notes-in-computer-science", label: "Springer LNCS" },
	{ id: "springer-mathphys", label: "Springer MathPhys" },
	{ id: "springer-socpsych-author-date", label: "Springer SocPsych" },
	{ id: "springer-vancouver", label: "Springer Vancouver" },
	{ id: "taylor-and-francis-chicago-author-date", label: "Taylor & Francis (Chicago)" },
	{ id: "taylor-and-francis-national-library-of-medicine", label: "Taylor & Francis (NLM)" },
	{ id: "the-institution-of-engineering-and-technology", label: "IET" },
	{ id: "the-lancet", label: "The Lancet" },
	{ id: "thieme", label: "Thieme (Deutsch)" },
	{ id: "trends", label: "Trends" },
	{ id: "turabian-author-date", label: "Turabian (author-date)" },
	{ id: "turabian-fullnote-8", label: "Turabian (full note)" },
] as const;

export const DEFAULT_CITATION_STYLE_ID = "ieee";

export function citationStyleLabel(id: string): string {
	return CITATION_STYLES.find((s) => s.id === id)?.label ?? id;
}
